name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '36 6 * * 1'

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
        contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: RUST_LOG=debug cargo test -- --nocapture
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - name: Code linter
      run: cargo clippy -- -D warnings
    - name: Style linter
      run: cargo fmt -- --check
